Feature/RI-1605
A2O-Dev/A2O-Dev-Chat pull request #3
Opened 2024-06-14 20:02 UTC by alvaroia2odev

2024-06-17 19:44 UTC, cancioalmaraza2o commented
@alvaroia2odev El PR tiene conflictos y tienen que resolverse, no puedes enviar un PR con conflictos...el revisor no las resuelve

2024-06-17 19:45 UTC, cancioalmaraza2o commented
Todas las funciones Php que añadiste tienen que llevar las Php Docs

2024-06-17 19:54 UTC, cancioalmaraza2o commented
@alvaroia2odev veo que estás haciendo uso de tailwind.

Elimina TODA la referencia a tailwind y sus clases y SOLO usa **material UI** y sus properties bajo la propiedad **sx**

2024-06-17 19:58 UTC, cancioalmaraza2o requested changes

2024-06-17 19:58 UTC, cancioalmaraza2o commented on app/Models/Message.php
> +    public function room()
Pon las php docs en cada función

2024-06-17 19:58 UTC, cancioalmaraza2o commented on database/migrations/2024_05_28_133400_create_rooms_table.php
> +            $table->string('name')->nullable(false);
El nullable(false) es redundante, por defecto un campo es no nullable.

Quitarlo

2024-06-17 19:58 UTC, cancioalmaraza2o commented on database/migrations/2024_05_28_133457_create_messages_table.php
> +            $table->unsignedBigInteger('room_id')->nullable(false);
El nullable(false) es redundante, por defecto un campo es no nullable.

Quitarlo

2024-06-17 19:58 UTC, cancioalmaraza2o commented on database/migrations/2024_05_28_133457_create_messages_table.php
> +            $table->unsignedBigInteger('user_id')->nullable(false);
El nullable(false) es redundante, por defecto un campo es no nullable.

Quitarlo

2024-06-17 19:58 UTC, cancioalmaraza2o commented on resources/js/Components/ChatContent.tsx
> +
En el comentario: [](https://a2odev.atlassian.net/browse/RI-1605?focusedCommentId=25150)

Se definió que no se añadirían fotos de perfil/avatars a la aplicación, eliminar esta funcionalidad de toda la aplicación

2024-06-17 19:58 UTC, cancioalmaraza2o commented on resources/js/Components/ChatItem.tsx
> +import React, { FC } from 'react'
En este archivo, por qué importas "React"?

2024-06-19 13:18 UTC, alvaroia2odev commented
Correcciones finalizadas

Adjunto analisis en sonarqube
<img width="1672" alt="Screenshot 2024-06-19 at 9 02 32 AM" src="https://github.com/A2O-Dev/A2O-Dev-Chat/assets/172307764/93540c78-b577-48c5-aba8-1bead22b1938">

2024-06-19 13:19 UTC, alvaroia2odev commented on app/Models/Message.php
> +    public function room()
Done

2024-06-19 13:20 UTC, alvaroia2odev commented on resources/js/Components/ChatContent.tsx
> +
Se quitaron los avatars

2024-06-20 11:56 UTC, cancioalmaraza2o commented
@alvaroia2odev estoy obteniendo errores en la compilación de los recursos

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/69e5bc87-773c-4234-b3df-9423018a25d3)

Porfavor solucionalo

2024-06-20 12:04 UTC, cancioalmaraza2o commented
# Observaciones al diseño

### Input de mensaje
El input del mensaje debería estar al final de la página, su posición no debería variar según la cantidad de mensajes.

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/f1951192-5059-48a0-85e9-f68994907da7)

### Lineas separadoras de chat

Añade un separador a los chats

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/dcd071f3-cbb9-4a11-aa05-ede4201efd9f)

### Sección no planificada

De dónde añadiste esta sección? No fue lo acordado en ticket. [https://a2odev.atlassian.net/browse/RI-1605?focusedCommentId=25150](https://a2odev.atlassian.net/browse/RI-1605?focusedCommentId=25150)

Eliminalo y aférrate al plan

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/b984498b-3702-4c2b-9274-4a0dbe1559cd)

2024-06-20 12:07 UTC, cancioalmaraza2o requested changes

2024-06-20 12:07 UTC, cancioalmaraza2o commented on app/Models/Room.php
> +     * The users that belong to the room.
PhpDoc @return olvidado

2024-06-20 12:07 UTC, cancioalmaraza2o commented on app/Models/User.php
> +     * The rooms that belong to the user.
PhpDoc @return olvidado

2024-06-20 12:07 UTC, cancioalmaraza2o commented on resources/js/Components/ChatContent.tsx
> +  avatar: string
Elimina la propiedad Avatar, no lo usaremos

2024-06-20 17:29 UTC, alvaroia2odev commented
Hola @cancioalmaraz , he realizado todos lo cambios solicitados.

<img width="1680" alt="Screenshot 2024-06-20 at 1 28 17 PM" src="https://github.com/A2O-Dev/A2O-Dev-Chat/assets/172307764/22b1d8a9-c427-44a5-b6c4-7e7d6d13de1d">

2024-06-24 12:00 UTC, cancioalmaraza2o commented
Hola @alvaroia2odev veo aún el problema de la compilación, por qué no lo has resuelto?

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/46c9b9cb-28b9-4be0-8ef4-8bbe401c0bd2)

2024-06-24 12:04 UTC, cancioalmaraza2o commented
En el tema del diseño, me gustaría que lo mejores, que lo hagas agradable a la vista, que se vea un diseño más profesional, ahora mismo se vé tosco.

![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/e2332b4b-563f-4cb9-a01a-e93fd7fd592f)

- Reducir un poco el tamaño del sidebar.
- Mejorar los colores de fondo de los componentes.
- He revisado que el diseño no es responsivo, hazlo responsivo.
- Mejoras en general para ver un diseño más agradable

Ojo que esta demo es para demostrar al cliente nuestras capacidades, así que tienes que hacerlo lo mejor posible

2024-06-24 12:07 UTC, cancioalmaraza2o commented
![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/115110418/9f726844-e464-477e-8f58-4a39dc5aac39)

 Mira el color que hace el focus al input, no contrasta en nada. Mejora todos estos detalles para que se vea agradable a la vista

2024-06-24 17:39 UTC, alvaroia2odev commented
Se realizaron los cambios solicitados. Y se acordo que la resposividad pasara al siguiente ticket.

2024-06-24 18:18 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +      </Box>}
aplica el formato de eslint

2024-06-24 18:18 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +          {selectedChat
aplica formateo de eslint

2024-06-24 18:24 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +          <AddCircle sx={{ position: 'absolute', width: '60px', height: '60px', left: 10, bottom: 10 }} />
**Componente para crear mensaje**
Al presionar  el boton de agregar no me sale el modal acordado en el comentario https://a2odev.atlassian.net/browse/RI-1605?focusedCommentId=25150

2024-06-24 19:43 UTC, alvaroia2odev commented
Se realizaron los cambios solicitados, se adjunta una captura del analisis de sonarqube 
![Screenshot from 2024-06-24 15-41-58](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/172307764/d1229f46-c4e0-4a38-aac2-1319896f5947)

2024-06-24 21:00 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +            {selectedChat
![Screenshot_2024-06-24_16-59-24](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/142403960/8e48514e-ee88-4078-836d-e58ea07e83ef)
Corrije los errores de eslint

2024-06-24 21:04 UTC, josdavid12 commented on resources/js/Components/ChatContent.tsx
> +            </Box>
Puedes agregar el box del usuario que envio su mensje porfavor asi no lo agregamos luego lo tendremos a mano  
![2024-06-24_17-04](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/142403960/04d77cdd-a8ed-420c-88e0-d2afbb1dcd9b)

2024-06-24 22:09 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +                  <TextField label='Mensaje' variant='outlined' type='text' fullWidth />
Elimina el item de mensaje ,manejaremos el layout creado para enviar el mensaje

2024-06-25 12:45 UTC, alvaroia2odev commented
Hola @josdavid12, he realizado todos los cambios solicitados.

2024-06-25 13:22 UTC, josdavid12 commented on resources/js/Pages/Dashboard.tsx
> +                Nuevo Mensaje
Los texto que estan en castellano lo puedes cambiar porfavor a ingles tenemos mezcla en la interfaz.

2024-06-25 13:24 UTC, josdavid12 commented on resources/js/Components/ChatContent.tsx
> +                <Typography variant='body2' sx={{ color: 'gray', ml: 2 }}>
Agregar contraste de color como el nombre de usuario

2024-06-25 13:46 UTC, alvaroia2odev commented on resources/js/Pages/Dashboard.tsx
> +                Nuevo Mensaje
Done

2024-06-25 13:46 UTC, alvaroia2odev commented on resources/js/Components/ChatContent.tsx
> +                <Typography variant='body2' sx={{ color: 'gray', ml: 2 }}>
Done

2024-06-25 13:47 UTC, alvaroia2odev commented
@josdavid12 he realizado los cambios solicitados

2024-06-25 20:23 UTC, alvaroia2odev commented
Se restablecieron los componentes por defecto @josdavid12

2024-06-25 21:00 UTC, josdavid12 commented on tailwind.config.js
> +    plugins: [],
No veo el tailwinf aplica en archivos creados por laravel no deja hacer scroll en perfil y los inputs estan diferentes alos creados por laravel
![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/142403960/c4385f6b-8d2d-45c1-add2-d64fc4cdf552)

2024-06-25 21:01 UTC, josdavid12 commented on resources/js/Pages/Auth/Login.tsx
> +          <PrimaryButton className='ms-4' disabled={processing} onClick={submit}>
Esta cambio se realizo por mui?

2024-06-25 21:01 UTC, josdavid12 commented on resources/js/Pages/Auth/ForgotPassword.tsx
> +          <PrimaryButton className='ms-4' disabled={processing} onClick={submit}>
Esta cambio se realizo por mui?

2024-06-25 21:01 UTC, josdavid12 commented on resources/js/Pages/Auth/Register.tsx
> +          <PrimaryButton className='ms-4' disabled={processing} onClick={submit}>
Esta cambio se realizo por mui?

2024-06-25 21:01 UTC, josdavid12 commented on resources/js/Pages/Auth/ResetPassword.tsx
> +          <PrimaryButton className='ms-4' disabled={processing} onClick={submit}>
Esta cambio se realizo por mui?

2024-06-25 21:01 UTC, josdavid12 commented on resources/js/Pages/Auth/VerifyEmail.tsx
> +          <PrimaryButton disabled={processing} onClick={submit}>Resend Verification Email</PrimaryButton>
Esta cambio se realizo por mui?

2024-06-25 21:05 UTC, josdavid12 commented on resources/js/Layouts/AuthenticatedLayout.tsx
> +    <Box
Se acordo que lo generado por laravel deberia continuar solo lo nuevo debia ir con mui,revisar por favor al parecer esta cuasando problemas de scroll

2024-06-26 12:10 UTC, alvaroia2odev commented
@josdavid12 Se restablecio el form plugin y los cambios solicitados.

2024-06-26 12:41 UTC, josdavid12 commented on resources/js/Layouts/AuthenticatedLayout.tsx
>    return (
Hay alguna motivo para no dejarlo en tailwind? El layout no se ve bien
![image](https://github.com/A2O-Dev/A2O-Dev-Chat/assets/142403960/bc9c51cb-e4c2-44ed-b0d9-0cc79f859661)

2024-06-26 15:40 UTC, alvaroia2odev commented
@josdavid12  Se procedio a cambiar el layout original y establecer en el dashboard la estructura del chat.

2024-06-28 15:37 UTC, josdavid12 commented on resources/js/Pages/Auth/Register.tsx
> +  useEffect(() => {
Quitalo por favor ,era parte del test

2024-06-28 15:52 UTC, alvaroia2odev commented on resources/js/Pages/Auth/Register.tsx
> +  useEffect(() => {
Done!

2024-06-28 15:57 UTC, merged